name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install -g @angular/cli
        npm install
        ng build --base-href="https://Mr-EmPee.github.io/MyAmazoon-Angular/"
    - name: Publishing
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Publishing Website"
        git push -f ${{ secrets.TOKEN }}@github.com/Mr-EmPee/MyAmazoon-Angular.git master:gh-pages
        git push -f https://Mr-EmPee:$@github.com/Mr-EmPee/MyAmazoon-Angular.git master:gh-pages